#include "Globals.h"
#include "Renderer.h"
#include "Config.h"
#include "ImageBufferMultipass.h"
#include "ImageBufferPreparedChunks.h"
#include "ImageBufferGpuPins.h"
#include <cmath>
#include <unordered_map>

// Direct rendering is exact and intentionally untouched for ordinary frames. Once a frame
// exceeds 100k submitted notes, however, millions of same-key bars can be completely hidden
struct DirectNoteCullState {
    unsigned frame = (std::numeric_limits<unsigned>::max)();
    bool active = false;
    bool disabled = false;
    int rows = 0;
    size_t raw = 0;
    size_t kept = 0;
    size_t dropped = 0;
    std::vector<int> next;
};

static std::unordered_map<Renderer*, DirectNoteCullState>& DirectNoteCullStates()
{
    static std::unordered_map<Renderer*, DirectNoteCullState> states;
    return states;
}

static int DirectNoteCullFind(DirectNoteCullState& state, int key, int row)
{
    const size_t base = (size_t)key * (size_t)(state.rows + 1);
    int root = row;
    while (state.next[base + root] != root)
        root = state.next[base + root];
    while (state.next[base + row] != row) {
        const int parent = state.next[base + row];
        state.next[base + row] = root;
        row = parent;
    }
    return root;
}

static bool DirectNoteCullContributes(
    DirectNoteCullState& state,
    const RootConstants& root,
    const TrackColor* colors,
    const NoteData& data)
{
    if (data.key >= 128 || data.channel >= 16 || data.track >= MaxTrackColors)
        return true;

    // Hidden notes are degenerated by note_vs.hlsl and therefore must not own
    // rows; once culling is active they can simply be omitted altogether.
    if (colors[(size_t)data.track * 16 + data.channel].darker == 0xFFFFFFFF)
        return false;

    const double span = (double)root.timespan;
    const double noteRows = (double)root.notes_cy;
    if (!(span > 0.0) || !(noteRows > 0.0) || state.rows <= 0)
        return true;

    const double length = (std::max)(0.0, (double)data.length);
    const double y = std::round(noteRows * (1.0 - (double)data.pos / span));
    const double cy = (std::max)(std::round(noteRows * length / span), (double)root.deflate);
    int row0 = (int)std::floor(y - cy);
    int row1 = (int)std::ceil(y);
    row0 = (std::max)(0, (std::min)(row0, state.rows));
    row1 = (std::max)(0, (std::min)(row1, state.rows));
    if (row1 <= row0)
        return false;

    int row = DirectNoteCullFind(state, (int)data.key, row0);
    if (row >= row1)
        return false;

    const size_t base = (size_t)data.key * (size_t)(state.rows + 1);
    while (row < row1) {
        state.next[base + row] = DirectNoteCullFind(state, (int)data.key, row + 1);
        row = state.next[base + row];
    }
    return true;
}

bool Renderer::PushNoteDataFiltered(NoteData data)
{
    auto& state = DirectNoteCullStates()[this];
    if (state.frame != m_uImageBufferFrame) {
        if (state.active && ((state.frame & 31u) == 0u)) {
            char log[160];
            sprintf_s(log, "direct:cull raw=%zu kept=%zu dropped=%zu rows=%d",
                state.raw, state.kept, state.dropped, state.rows);
            HeartbeatLog(log);
        }
        state.frame = m_uImageBufferFrame;
        state.active = false;
        state.disabled = false;
        state.rows = 0;
        state.raw = 0;
        state.kept = 0;
        state.dropped = 0;
        state.next.clear();
    }

    ++state.raw;
    static constexpr size_t kDirectCullThreshold = 100000;
    if (!state.active && !state.disabled && state.raw > kDirectCullThreshold) {
        // Warp moves corners after NoteData reaches the shader, so CPU row
        // ownership cannot safely predict it. Keep the exact path in that mode.
        if (m_RootConstants.fWarp > 0.0f || m_RootConstants.timespan <= 0.0f ||
            m_RootConstants.notes_cy <= 0.0f) {
            state.disabled = true;
        } else {
            state.rows = (std::min)((std::max)((int)std::ceil(std::fabs(m_RootConstants.notes_cy)), 64),
                ImageBufferPreparedMaxRows);
            try {
                state.next.resize((size_t)128 * (size_t)(state.rows + 1));
                for (int key = 0; key < 128; ++key) {
                    const size_t base = (size_t)key * (size_t)(state.rows + 1);
                    for (int row = 0; row <= state.rows; ++row)
                        state.next[base + row] = row;
                }

                std::vector<NoteData> seed;
                seed.swap(m_vNotesIntermediate);
                m_vNotesIntermediate.reserve((std::min)(
                    seed.size(), (size_t)128 * (size_t)state.rows));
                state.kept = 0;
                state.dropped = 0;
                for (const NoteData& existing : seed) {
                    if (DirectNoteCullContributes(state, m_RootConstants, m_TrackColors, existing)) {
                        m_vNotesIntermediate.push_back(existing);
                        ++state.kept;
                    } else {
                        ++state.dropped;
                    }
                }
                state.active = true;
            } catch (...) {
                // This is purely an optimization. If its small row table cannot
                // be allocated, retain the original direct renderer unchanged.
                state.next.clear();
                state.disabled = true;
                state.active = false;
            }
        }
    }

    if (!state.active) {
        ++state.kept;
        return false;
    }

    if (DirectNoteCullContributes(state, m_RootConstants, m_TrackColors, data)) {
        ++state.kept;
        return false;
    }

    ++state.dropped;
    return true;
}

namespace ImGui {
static bool s_PGFAInVizPreferences = false;

static bool PGFABeginTabItem(const char* label, bool* p_open = nullptr, ImGuiTabItemFlags flags = 0)
{
    const bool open = BeginTabItem(label, p_open, flags);
    if (open && label && strcmp(label, "Viz") == 0)
        s_PGFAInVizPreferences = true;
    return open;
}

static void PGFAEndTabItem()
{
    EndTabItem();
    s_PGFAInVizPreferences = false;
}

static bool PGFAImageBufferCheckbox(const char* label, bool* value)
{
    if (s_PGFAInVizPreferences && label && strcmp(label, "Bounce stats to the beat") == 0)
        return false;

    const bool wasEnabled = value && *value;
    const bool changed = Checkbox(label, value);
    if (label && strcmp(label, "Visual Buffer Notes") == 0) {
        static bool initialized = false;
        VizSettings& viz = Config::GetConfig().GetVizSettings();
        if ((!initialized && value && *value) || (changed && !wasEnabled && value && *value)) {
            ImageBufferPreparedSetWaitBeforePlayback(true);
            viz.bWaitDenseBuffers = true;
        }
        initialized = true;

        ImGui::Indent();
        ImGui::BeginDisabled(!*value);
        bool waitForDense = ImageBufferPreparedGetWaitBeforePlayback();
        if (Checkbox("Wait for dense buffers before playback", &waitForDense)) {
            ImageBufferPreparedSetWaitBeforePlayback(waitForDense);
            viz.bWaitDenseBuffers = waitForDense;
            if (!waitForDense)
                ImageBufferPreparedCancelPlaybackGate();
        }
        if (ImGui::IsItemHovered())
            ImGui::SetTooltip("Prepares dense visual-buffer chunks before a requested playback start.");
        ImGui::EndDisabled();
        ImGui::Unindent();
    }
    return changed;
}

static bool PGFASliderInt(const char* label, int* v, int v_min, int v_max,
                          const char* format = "%d", ImGuiSliderFlags flags = 0)
{
    if (s_PGFAInVizPreferences && label && strcmp(label, "Low Activity Threshold") == 0)
        return false;
    return SliderInt(label, v, v_min, v_max, format, flags);
}
}

// Compile the existing shared renderer unchanged under a legacy name for the one method this
// file replaces. These aliases add the Image Buffer wait switch and hide RenderMode-only
#define BeginTabItem PGFABeginTabItem
#define EndTabItem PGFAEndTabItem
#define Checkbox PGFAImageBufferCheckbox
#define SliderInt PGFASliderInt
#define ImageBufferRenderChunk ImageBufferRenderChunkLegacy
#include "RendererBaseLegacy.inc"
#undef ImageBufferRenderChunk
#undef SliderInt
#undef Checkbox
#undef EndTabItem
#undef BeginTabItem

bool Renderer::ImageBufferRenderChunk(long long chunk, const NoteData* notes, unsigned noteCount)
{
    // Remember the active renderer so a later Play request can explicitly wake
    // full-song preparation even if the current lookahead is already cached.
    ImageBufferPrewarmRendererSeen(this);

    // A dense chunk owned by the CPU preparation queue deliberately supplies no notes until its
    // compact representation is ready. Do not let an empty request become a permanently cached
    if (ImageBufferPreparedRenderPending(this, chunk))
        return false;

    if (!notes)
        noteCount = 0;
    if (ImageBufferChunkCached(chunk))
        return true;

    // A pass this size is large enough to amortize state changes but bounded
    // enough that a multi-million-note chunk cannot monopolize one frame.
    static constexpr size_t kImageBufferNotesPerPass = 65536;
    static constexpr size_t kImageBufferNotesPerFrame = 65536;

    auto& state = ImageBufferMPGet(this);
    if (state.generation != m_ullImageBufferGeneration) {
        state = ImageBufferMultipassState{};
        state.generation = m_ullImageBufferGeneration;
        state.frame = m_uImageBufferFrame;
    }

    if (state.frame != m_uImageBufferFrame) {
        state.frame = m_uImageBufferFrame;
        state.frameNotes = 0;
        // Normally EndScene clears this after recording the previous pass. If
        // the backend aborted, retry the same cursor rather than skipping it.
        state.requestQueued = false;
        state.backendActive = false;
        state.requestSlot = -1;
        state.requestChunk = ImageBufferInvalidChunk;
        state.requestCount = 0;
        state.requestClear = false;
        state.requestFinalize = false;
    }

    // Only one GPU chunk pass is queued in a frame. This also prevents the
    // existing 8-chunk lookahead loop from turning into 8 dense GPU jobs.
    if (state.requestQueued)
        return false;

    // A newly-visible missing chunk takes priority over an unfinished future chunk. Release the
    // reserved slot; its next first pass will clear stale color/depth before restarting from note
    if (state.slot >= 0 && state.chunk != chunk) {
        if (state.slot < (int)ChunkPoolSize &&
            m_ChunkCache[state.slot].generation == m_ullImageBufferGeneration &&
            m_ChunkCache[state.slot].chunk == ImageBufferInvalidChunk - 1) {
            m_ChunkCache[state.slot].chunk = ImageBufferInvalidChunk;
            m_ChunkCache[state.slot].generation = 0;
        }
        state.chunk = ImageBufferInvalidChunk;
        state.slot = -1;
        state.cursor = 0;
        state.total = 0;
        state.notes.clear();
    }

    if (noteCount > 0 && state.frameNotes >= kImageBufferNotesPerFrame)
        return false;

    if (state.slot < 0) {
        int slot = -1;
        for (unsigned i = 0; i < ChunkPoolSize; ++i) {
            if (m_ChunkCache[i].generation != m_ullImageBufferGeneration ||
                m_ChunkCache[i].chunk == ImageBufferInvalidChunk) {
                slot = (int)i;
                break;
            }
        }
        if (slot < 0) {
            unsigned oldest = UINT_MAX;
            for (unsigned i = 0; i < ChunkPoolSize; ++i) {
                if (m_ChunkCache[i].generation != m_ullImageBufferGeneration ||
                    m_ChunkCache[i].chunk == ImageBufferInvalidChunk ||
                    m_ChunkCache[i].chunk == ImageBufferInvalidChunk - 1 ||
                    ImageBufferChunkPinned(this, m_ChunkCache[i].chunk))
                    continue;
                if (m_ChunkCache[i].lastUsed < oldest) {
                    oldest = m_ChunkCache[i].lastUsed;
                    slot = (int)i;
                }
            }
        }
        if (slot < 0)
            return false;

        m_ChunkCache[slot].chunk = ImageBufferInvalidChunk - 1;
        m_ChunkCache[slot].generation = m_ullImageBufferGeneration;
        state.slot = slot;
        state.chunk = chunk;
        state.cursor = 0;
        state.notes.clear();
        if (noteCount > 0) {
            state.notes.assign(notes, notes + noteCount);
            state.collectChunk = chunk;
            state.collectCalls = 1;
        }
        state.total = state.notes.size();
    } else if (noteCount > 0 && noteCount != state.total) {
        state.cursor = 0;
        state.notes.assign(notes, notes + noteCount);
        state.total = state.notes.size();
        state.collectChunk = chunk;
        state.collectCalls = 1;
    }

    if (state.cursor > state.total)
        state.cursor = 0;

    const size_t remaining = state.total - state.cursor;
    const size_t frameRemaining = kImageBufferNotesPerFrame - state.frameNotes;
    const size_t passCount = remaining == 0
        ? 0
        : min(remaining, min(kImageBufferNotesPerPass, frameRemaining));

    if (remaining > 0 && passCount == 0)
        return false;

    const unsigned noteOffset = (unsigned)m_vChunkNotes.size();
    if (passCount > 0)
        m_vChunkNotes.insert(m_vChunkNotes.end(),
            state.notes.data() + state.cursor,
            state.notes.data() + state.cursor + passCount);

    m_vChunkBuilds.push_back({ chunk, noteOffset, (unsigned)passCount });
    state.requestQueued = true;
    state.requestSlot = state.slot;
    state.requestChunk = chunk;
    state.requestCount = (unsigned)passCount;
    state.requestClear = (state.cursor == 0);
    state.requestFinalize = (state.cursor + passCount >= state.total);
    state.frameNotes += passCount;

    return state.requestFinalize;
}
